### PR TITLE
1.19 port

### PR DESCRIPTION
**Pull request by Raqbit**
## Changes
- Bump gradle to `7.4.2`
- Update forge to `41.0.45`
- Update fabric to `0.56.1+1.19`
  - Update fabric-loom gradle plugin to `0.12-SNAPSHOT`
  - Update fabric-loader to `0.14.8`
- Update parchment to `1.18.2-2022.06.19`
- Update JEI dependency to `11.0.0.206`
- Update REI dependency to `9.0.491`

## Functional changes (as far as I know)
When using the forge version of the mod, moving around in Thatch will now behave like water. The new Forge FluidType system only allows you to completely replace movement code, not tell it to use the "normal" movement code that is used when not in a fluid.

## Misc. notes

- JEI now also has a Fabric version, so this might be something that DecorativeBlocks could add support for.
- Updated the forge fog rendering code to use the new FluidType system instead of a FogRenderer mixin

### CODE REVIEW

**Comment by braunly** [comment]
Thank you. Works fine on Fabric 1.19.2

**Comment by lilypuree** [comment]
can you change the pr to push to the new 1.19 branch?

**Comment by Raqbit** [comment]
> can you change the pr to push to the new 1.19 branch?

Done! Though perhaps this will need to be updated to a newer forge & fabric version, as I heard a lot has changed in the meanwhile.

**Comment by woalk** [comment]
> > can you change the pr to push to the new 1.19 branch?
> 
> Done! Though perhaps this will need to be updated 1.19.2 & to a newer forge & fabric version, as I heard a lot has changed in the meanwhile?

It works without change on 1.19.2.

**Comment by Raqbit** [comment]
> > > can you change the pr to push to the new 1.19 branch?
> > 
> > 
> > Done! Though perhaps this will need to be updated 1.19.2 & to a newer forge & fabric version, as I heard a lot has changed in the meanwhile?
> 
> It works without change on 1.19.2.

Ah, good to know, thank you!

**Comment by braunly** [comment]
@lilypuree crashing on Fabric server 1.19.2 with REI 9.1.520
https://gist.github.com/braunly/d65cb0eb47aa4f0f41dc935587953b26

Fixed by changing `rei_common` to `rei_client` in fabric.mod.json

**Pull request merged**
